version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    github-actions:
      docker:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    groups:
      docker:
        patterns:
          - "*"
  - package-ecosystem: gomod
    open-pull-requests-limit: 10
    directory: /
    schedule:
      interval: daily
    groups:
      docker:
        patterns:
          - "github.com/docker/*"
          - "github.com/moby/*"
      testcontainers:
        patterns:
          - "github.com/testcontainers/*"
      common:
        patterns:
          - "*"