name: Check Go version of dependencies
on:
  pull_request:
    paths:
      - 'go.mod'
  workflow_dispatch:

jobs:
  check-go-versions:
    name: Check Go version of dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4.1.0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Check that dependencies doesn't use Go 1.21
        run: |
          go mod tidy
          if [ grep -q "go 1.21" go.mod ]; then
            echo "One of new dependencies required Go '1.21'. Use 'go get go@1.20' to fix that."
            exit 1
          fi