name: maximize-build-disk-space-test
on:
  workflow_dispatch:

jobs:
  maximize-build-disk-space-test:
    name: maximize-build-disk-space-test
    runs-on: ubuntu-latest
    steps:
      - name: "free size"
        run: |
          du -sh /home/* 2>&1 | grep -v  '^du:'
          du -sh /home/runner/* 2>&1 | grep -v  '^du:'
          

      - name: Maximize build space
        uses: easimon/maximize-build-space@v7
        with:
          root-reserve-mb: 35840 # Required for Goreleaser
          remove-android: 'true'
          remove-docker-images: 'true'
          remove-dotnet: 'true'

      - name: Checkout code
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: "free size"
        run: |
          df -h
          echo "tmp folder:"
          df -h /tmp       
