name: tmp-check
on:
  workflow_dispatch:

jobs:
  tmp-check:
    name: Tmp check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Check dir
        run: |
          pwd
          ls -hl .

      - name: Check tmp dir size
        run: |
          df -h /tmp         
